/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CheckCursorType */

#ifndef _Included_CheckCursorType
#define _Included_CheckCursorType
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     CheckCursorType
	* Method:    CheckCursorType
	* Signature: (I)Z
	*/
	JNIEXPORT jboolean JNICALL Java_CheckCursorType_CheckCursorType
	(JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif

